branchName: '${issue.number}'
branches:
 - label: '*'
   prefix: feature#
autoCloseIssue: true
commentMessage: 'Branch (${branchName})[${issue.url}]가 생성되었습니다! 우리팀 천재 (${assignee.login}}[assignee.html_url], 이번 이슈도 파이팅 🔥'
