require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'CrystalMineFrontend' do
  $RNFirebaseAnalyticsWithoutAdIdSupport=true

  config = use_native_modules!
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  # Uncomment the next line if you need Firebase Messaging
  # pod 'Firebase/Messaging', :modular_headers => true

  # Uncomment the next line if you are using push notifications
  # pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )
  
  target 'CrystalMineFrontendTests' do
    inherit! :complete
    # Pods for testing
  end

  # Uncomment the next line if you want to use Flipper
  # use_flipper!()

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
end
